# Example api requests

## Media resource 

## Get all media items

GET http://localhost:3000/api/media

### Get media item by id

GET http://localhost:3000/api/media/9632?format=plain

### Not found media item by id

GET http://localhost:3000/api/media/9632

### Get media item by id

GET http://localhost:3000/api/media/4

### Create media item

POST http://localhost:3000/api/media
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJpYXQiOjE3MzI1MjQ5MzQsImV4cCI6MTczMjYxMTMzNH0.Mjfphzf17fNb1FnN8_rUf9I9f8tyTBdLcsZUliMH1Sk
Content-Type: multipart/form-data; boundary=----Boundary

------Boundary
Content-Disposition: form-data; name="title"

My cute cat Popoliini
------Boundary
Content-Disposition: form-data; name="description"

My cat is very cute
------Boundary
Content-Disposition: form-data; name="user_id"

5
------Boundary
Content-Disposition: form-data; name="file"; filename="image.png"
Content-Type: pdf

< ./test-cat.png
------Boundary--

### update a media item

PUT http://localhost:3000/api/media/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJpYXQiOjE3MzIxODExNDQsImV4cCI6MTczMjI2NzU0NH0.q-J570gBexGuglkr6v0YkcpWneLYijDn95V6STx2vtg
Content-Type: application/json

{
    "title": "My cat",
    "description": "my very cute cat"
}

### Delete a media item

DELETE http://localhost:3000/api/media/1

## User authentication

### Register a new user

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "popopopo",
    "password": "Mr.Popo_kissa",
    "email": "kissa@metropolia.fi"
}

### Log in

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "popoliinikissa",
    "password": "Mr.Popo_kissa"
}

### Get my user info

GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMiwiaWF0IjoxNzMyMTgwNTg0LCJleHAiOjE3MzIyNjY5ODR9.ik8figS7opE8k7G5cW_uFgeMvgkR6xUZwdYVglp30Ek

## User resource

### Get all users

GET http://localhost:3000/api/users

### Get user by id

GET http://localhost:3000/api/users/1

### Create a new user

POST http://localhost:3000/api/users
Content-Type: application/json

{
    "user_id": "",
    "username": "Popodii",
    "password": "********",
    "email": "Popo1000@example.com",
    "user_level_id": 2
}

### Update a user

PUT http://localhost:3000/api/users/19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOSwiaWF0IjoxNzMyNjA5MzY3LCJleHAiOjE3MzI2OTU3Njd9.UnORCAD6MpXsoFx52oA8OQQSHZtR0j4VCL-qYfKpwG4
Content-Type: application/json

{
    "username": "Maumau",
    "password": "********",
    "email": "miau@metropolia.fi"
}

### Delete a user

DELETE http://localhost:3000/api/users/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMiwiaWF0IjoxNzMyMTgwNTg0LCJleHAiOjE3MzIyNjY5ODR9.ik8figS7opE8k7G5cW_uFgeMvgkR6xUZwdYVglp30Ek

## Comment resource

### Get all comments

GET http://localhost:3000/api/comments


### Get comment by id

GET http://localhost:3000/api/comments/4

### Get a comment by user id

GET http://localhost:3000/api/comments/users/1

### Create a new comment

POST http://localhost:3000/api/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOSwiaWF0IjoxNzMyNjEwMzAxLCJleHAiOjE3MzI2OTY3MDF9.QZ4QVD_2_pkrudbVMnqzJIfDLTXe6rhI8-3oq53sW2E
Content-Type: application/json

{
    "comment_id": "",
    "user_id": "",
    "media_id": 10,
    "comment_text": "Omg love it!",
    "created_at": "2021-12-11T06:00:41.000Z"
}

### Update a comment

PUT http://localhost:3000/api/comments/18
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOSwiaWF0IjoxNzMyNjEwMzAxLCJleHAiOjE3MzI2OTY3MDF9.QZ4QVD_2_pkrudbVMnqzJIfDLTXe6rhI8-3oq53sW2E
Content-Type: application/json

{   
    "comment_id": "",
    "comment_text": "Wau, amazing!",
    "created_at": "2021-12-11T06:00:41.000Z"
}

### Delete a comment

DELETE http://localhost:3000/api/comments/13
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJpYXQiOjE3MzIxODUxNzEsImV4cCI6MTczMjI3MTU3MX0.uaBceOmNB10sqk3U2YOaE5oLtn1Sb2yIl6uFmZSgRHc
